config/routes.rb
Rails.application.routes.draw do
  mount API::Base => '/api'
  mount Resque::Server, :at => "/resque"

  resources :stores do
    member do
      get :statistic
      get :stat_tables
    end
  end
  resources :documents

  root 'stores#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :store
  has_many :rows, :dependent => :destroy

  has_attached_file :file
  validates_attachment_content_type :file, :content_type => %w(text/csv)
  validates :store_id, :presence => true

  after_save :create_rows_from_file

  private

  def create_rows_from_file
    # only for heroku hack
    # heroku destroys uploaded files after the request is complet
    if ENV["HEROKU"] == '1'
      if self.file.present?
        CreateRowsService.new(self).perform
        UpdateStatisticWorker.enqueue(id)
      end
    else
      CreateRowsWorker.enqueue(self.id) if self.file.present?
    end
  end
end

app/models/row.rb
class Row < ActiveRecord::Base
  FIELDS = [:visit_data, :mac_address, :a, :b, :c, :d, :e, :f, :g, :h]

  belongs_to :document
end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
  belongs_to :store

  def rows
    store.rows.where(visit_data: (beginning_of_period..end_of_period))
  end

  def repeating_visitors_percent
    (100*repeating_visitors_count/unique_visitors_count.to_f).round(2)
  end

  def update_to_latest_data
    if rows.count > 0
      update(avg_dwell_time: new_avg_dwell_time,
             unique_visitors_count: new_unique_visitors_count,
             repeating_visitors_count: new_repeating_visitors_count)
    end
  end

  private

  def new_avg_dwell_time
    time_arr = rows.pluck(:a)
    time_arr.sum.to_f/time_arr.size
  end

  def new_unique_visitors_count
    visitors.uniq.count
  end

  def new_repeating_visitors_count
    visitors.select{ |e| visitors.count(e) > 1 }.uniq.count
  end

  def visitors
    @visitors ||= rows.pluck(:mac_address)
  end

  def beginning_of_period
    period_start.send("beginning_of_#{period_type}")
  end

  def end_of_period
    period_end.send("end_of_#{period_type}")
  end
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :documents, :dependent => :destroy
  has_many :rows, through: :documents
  has_many :statistics

  validates :name, :presence => true
end

app/controllers/api/base.rb
module API
  class Base < Grape::API
    mount API::StatisticApi
    mount API::DocumentApi
  end
end

app/controllers/api/document_api.rb
module API
  class DocumentApi < Grape::API
    # Set all output formats to json
    # NOTE: always functions should return hash!!!
    format :json

    resource :document do
      post '/' do
        document = Document.new
        document.file = params[:document][:file]
        document.save
      end
    end
  end
end

app/controllers/api/statistic.rb
module API
  class Statistic < Grape::API
    # Set all output formats to json
    # NOTE: always functions should return hash!!!
    format :json

    resource :statistic do
      before do
        @ss = StatisticService.new(sub_domain: params[:sub])
      end

      get :average_dwell_time do
        @ss.average_dwell_time
      end

      get :unique_visitors do
        @ss.unique_visitors_count
      end

      get :repeating_visitors do
        @ss.repeating_visitors_percent
      end
    end
  end
end

app/controllers/api/statistic_api.rb
module API
  class StatisticApi < Grape::API
    # Set all output formats to json
    # NOTE: always functions should return hash!!!
    format :json

    resource :statistic do
      before do
        store = Store.find(params[:store_id])
        @statistic_service = StatisticService.new(store, sub_domain: params[:sub_domain])
      end

      get :average_dwell_time do
        @statistic_service.average_dwell_time
      end

      get :unique_visitors do
        @statistic_service.unique_visitors_count
      end

      get :repeating_visitors do
        @statistic_service.repeating_visitors_percent
      end

      get :all do
        { average_dwell_time: @statistic_service.average_dwell_time,
          unique_visitors_count: @statistic_service.unique_visitors_count,
          repeating_visitors_percent: @statistic_service.repeating_visitors_percent
        }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:file, :store_id)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy, :statistic, :stat_tables]
  before_action :set_sub_domain, only: [:statistic, :stat_tables]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def statistic
  end

  def stat_tables
    render :layout => 'tables'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name)
    end

    def set_sub_domain
      @sub_domain = params[:sub_domain] || 'month'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/_form.html.slim
= simple_form_for @document, :html => { :class => "form-horizontal" } do |f|
  = f.association :store, collection: Store.first(10)
  = error_span(@document[:store_id])

  = f.input :file, as: :file
  = error_span(@document[:file])

  = f.button :submit, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), documents_path, :class => 'btn btn-default'

app/views/documents/edit.html.slim
- model_class = Document
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/documents/index.html.slim
- model_class = Document
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:file_file_name)
      th= model_class.human_attribute_name(:file_content_type)
      th= model_class.human_attribute_name(:file_file_size)
      th= model_class.human_attribute_name(:file_updated_at)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @documents.each do |document|
      tr
        td= link_to document.id, document_path(document)
        td= document.file_file_name
        td= document.file_content_type
        td= document.file_file_size
        td= document.file_updated_at
        td=l document.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_document_path(document), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), document_path(document), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_document_path, :class => 'btn btn-primary'

app/views/documents/new.html.slim
- model_class = Document
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/documents/show.html.slim
- model_class = Document
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:file_file_name) + ':'
  br
  = @document.file_file_name
p
  strong= model_class.human_attribute_name(:file_content_type) + ':'
  br
  = @document.file_content_type
p
  strong= model_class.human_attribute_name(:file_file_size) + ':'
  br
  = @document.file_file_size
p
  strong= model_class.human_attribute_name(:file_updated_at) + ':'
  br
  = @document.file_updated_at

= link_to t('.back', :default => t("helpers.links.back")), documents_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_document_path(@document), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), document_path(@document), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoreStat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="span12">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/tables.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Table With Embedded Line Chart</title>
  <%= stylesheet_link_tag    'tables', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'tables', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/statistic/index.html.erb
<div style="width: 50%; margin: 0 auto;">
  <ul class="nav nav-tabs">
    <li class="active">
      <a href="#tab1" data-toggle="tab">
        Charts
      </a>
    </li>
    <li>
      <a href="#tab2" data-toggle="tab">
        Tables
      </a>
    </li>
  </ul>
  <div class="tab-content">
    <div id="tab1" class="tab-pane active">
      <div class="btn-group">
        <button type="button" class="btn btn-primary">Period</button>
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><a href="?sub=month">Per month</a></li>
          <li><a href="?sub=week">Per week</a></li>
          <li><a href="?sub=day">Per day</a></li>
        </ul>
        <div style="float:left;margin: 0 10px;">
          <button class="btn" id="navigationSelector-previous">Previous</button>
          <button class="btn" id="navigationSelector-next">Next</button>
          <div class="source"></div>
        </div>
      </div>
      <div class="stat-block">
        <h1>average dwell time</h1>
        <div id="average_dwell_time"></div>
      </div>
      <div class="stat-block">
        <h1>unique visitors</h1>
        <div id="unique_visitors"></div>
      </div>
      <div class="stat-block">
        <h1>repeating visitors percent</h1>
        <div id="repeating_visitors"></div>
      </div>
    </div>
    <div id="tab2" class="tab-pane">
       <iframe frameborder="0" width="1000" height="600" src=<%= "stat_tables?sub=#{@sub_domain}" %>>
       </iframe>
    </div>
  </div>
</div>
<style type="text/css">
  .stat-block {
    padding-bottom: 30px;
  }
  .tab-content {
    padding-top: 20px;
  }
</style>
<script type="text/javascript">
$(document).ready(function() {
  var baseOptions = {
    subDomain: "<%= raw @sub_domain %>" || "month",
    start: new Date(2014, 0),
    cellSize: 25,
    // subDomainTextFormat: subDomainTextFormat(),
    tooltip: true
  };
  if(baseOptions.subDomain==='month'){
    $.extend(baseOptions, { domain: "year", range: 1});
  }
  if(baseOptions.subDomain==='week'){
    $.extend(baseOptions, { domain: "month", range: 4 });
  }
  if(baseOptions.subDomain==='day'){
    $.extend(baseOptions, { domain: "month", range: 4});
  }

  var average_dwell_time = new CalHeatMap();
  average_dwell_time.init($.extend({}, baseOptions, {
    itemSelector: "#average_dwell_time",
    data: "api/statistic/average_dwell_time?sub=" + baseOptions.subDomain,
    legend: [20, 40, 60, 100],
    itemName: ["minute", "minutes"]
  }));

  var unique_visitors = new CalHeatMap();
  unique_visitors.init($.extend({}, baseOptions, {
    itemSelector: "#unique_visitors",
    data: "api/statistic/unique_visitors?sub=" + baseOptions.subDomain,
    legend: [5, 10, 50, 100],
    itemName: ["visitor", "visitors"]
  }));

  var repeating_visitors = new CalHeatMap();
  repeating_visitors.init($.extend({}, baseOptions, {
    itemSelector: "#repeating_visitors",
    data: "api/statistic/repeating_visitors?sub=" + baseOptions.subDomain,
    legend: [10, 30, 60, 90],
    itemName: ["%", "%"]
  }));

  var allCharts = [average_dwell_time, unique_visitors, repeating_visitors];

  $("#navigationSelector-next").on("click", function(event) {
    $.map(allCharts, function( val, i ) { val.next(baseOptions.range); });
  });

  $("#navigationSelector-previous").on("click", function(event) {
    $.map(allCharts, function( val, i ) { val.previous(baseOptions.range); });
  });

  function subDomainTextFormat(){
    if($( "#stat-period").val() == 'week'){
      return "%d";
    }
    else {
      return "%" + $( "#stat-period").val().substring(0,1);
    }
  };
});
</script>

app/views/statistic/stat_tables.html.erb
<div id="datatable"></div>

<style>
table {
  border-collapse: collapse;
}
th {
  border-bottom: 2px solid #ddd;
  padding: 8px;
  font-weight: bold;
}
td {
  padding: 8px;
  border-top: 1px solid #ddd;
}
#chart {
  padding: 0px;
}
.xaxislabel {
  font-size: 9px;
}
</style>

<script>
var rows = []
var subDomain = "<%= raw @sub_domain %>";
var formatdate;
if(subDomain==='month'){
  formatdate = d3.time.format("%b %Y");
} else {
  formatdate = d3.time.format("%b %d %Y");
}
d3.json("api/statistic/all?sub="+subDomain, function(error, csv) {
  d3.keys(csv.average_dwell_time).forEach(function(key) {
    row = {};
    row.dt = formatdate(new Date(parseInt(key)*1000));
    row.adt = parseFloat(csv.average_dwell_time[key]).toFixed(2);
    row.uvc = parseFloat(csv.unique_visitors_count[key]).toFixed(2);
    row.rvp = parseFloat(csv.repeating_visitors_percent[key] || 0.0).toFixed(2);
    rows.push(row);
  });

  var table = d3.select("#datatable").append("table");
      thead = table.append("thead");
      tbody = table.append("tbody");

  thead.append("th").text("Date");
  thead.append("th").text("Avg time");
  thead.append("th").text("Unique visitors");
  thead.append("th").text("Repeating visitors (%)");
  thead.append("th").text("");

  var tr = tbody.selectAll("tr")
      .data(rows)
      .enter().append("tr");

  var td = tr.selectAll("td")
        .data(function(d) { return [d.dt, d.adt, d.uvc, d.rvp]; })
      .enter().append("td")
        .text(function(d) { return d; });

  var width = 80,
      height = d3.select("table")[0][0].clientHeight,
      mx = 10,
      radius = 2;

  var addChart = function(type){
    // Now add the chart column
    d3.select("#datatable tbody tr").append("td")
      .attr("id", "chart"+type)
      .attr("width", width + "px")
      .attr("rowspan", rows.length);

    var chart = d3.select("#chart"+type).append("svg")
      .attr("class", "chart")
      .attr("width", width)
      .attr("height", height);

    var maxMu = 0;
    var minMu = Number.MAX_VALUE;
    for (i=0; i < rows.length; i++) {
      if (rows[i][type] > maxMu) { maxMu = rows[i][type]; }
      if (rows[i][type] < minMu) { minMu = rows[i][type]; }
    }

    var dates = rows.map(function(t) { return t.dt; });

    var xscale = d3.scale.linear()
      .domain([minMu, maxMu])
      .range([mx, width-mx])
      .nice();

    var yscale = d3.scale.ordinal()
      .domain(dates)
      .rangeBands([0, height]);

    chart.selectAll(".xaxislabel")
        .data(xscale.ticks(2))
      .enter().append("text")
        .attr("class", "xaxislabel")
        .attr("x", function(d) { return xscale(d); })
        .attr("y", 10)
        .attr("text-anchor", "middle")
        .text(String)

    chart.selectAll(".xaxistick")
        .data(xscale.ticks(2))
      .enter().append("line")
        .attr("x1", function(d) { return xscale(d); })
        .attr("x2", function(d) { return xscale(d); })
        .attr("y1", 10)
        .attr("y2", height)
        .attr("stroke", "#eee")
        .attr("stroke-width", 1);

    chart.selectAll(".line")
        .data(rows)
      .enter().append("line")
        .attr("x1", function(d) { return xscale(d[type]); })
        .attr("y1", function(d) { return yscale(d.dt) + yscale.rangeBand()/2; })
        .attr("x2", function(d,i) { return rows[i+1] ? xscale(rows[i+1][type]) : xscale(d[type]); })
        .attr("y2", function(d,i) { return rows[i+1] ? yscale(rows[i+1].dt) + yscale.rangeBand()/2 : yscale(d.dt) + yscale.rangeBand()/2; })
        .attr("stroke", "#777")
        .attr("stroke-width", 1);

    var pt = chart.selectAll(".pt")
        .data(rows)
      .enter().append("g")
        .attr("class", "pt")
        .attr("transform", function(d) { return "translate(" + xscale(d[type]) + "," + (yscale(d.dt) + yscale.rangeBand()/2) + ")"; });

    pt.append("circle")
        .attr("cx", 0)
        .attr("cy", 0)
        .attr("r", radius)
        .attr("opacity", .5)
        .attr("fill", "#ff0000");
  };

  addChart('adt');
  addChart('uvc');
  addChart('rvp');
});
</script>
</body>
</html>

app/views/stores/_form.html.slim
= simple_form_for @store, :html => { :class => "form-horizontal" } do |f|
  = f.input :name
  = error_span(@store[:name])
  = f.button :submit, :class => 'btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), stores_path, :class => 'btn btn-default'

app/views/stores/edit.html.slim
- model_class = Store
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stores/index.html.slim
- model_class = Store
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @stores.each do |store|
      tr
        td= link_to store.id, store_path(store)
        td= store.name
        td=l store.created_at
        td
          = link_to 'Statistic', statistic_store_path(store), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_store_path(store), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), store_path(store), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_store_path, :class => 'btn btn-primary'

app/views/stores/new.html.slim
- model_class = Store
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stores/show.html.slim
- model_class = Store
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @store.name

= link_to t('.back', :default => t("helpers.links.back")), stores_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_store_path(@store), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), store_path(@store), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/stores/stat_tables.html.slim
#datatable data-store-id=@store.id data-sub-domain=@sub_domain

app/views/stores/statistic.html.slim
#centered-block data-sub-domain=@sub_domain data-store-id=@store.id
  ul.nav.nav-tabs
    li.active
      a data-toggle="tab" href="#tab1"
        | Charts
    li
      a data-toggle="tab" href="#tab2"
        | Tables
  .tab-content
    #tab1.tab-pane.active
      .btn-group
        button.btn.btn-primary type="button"  Period
        button.btn.btn-primary.dropdown-toggle data-toggle="dropdown" type="button"
          span.caret
          span.sr-only Toggle Dropdown
        ul.dropdown-menu role="menu"
          li
            a href="?sub_domain=month"  Per month
          li
            a href="?sub_domain=week"  Per week
          li
            a href="?sub_domain=day"  Per day
        .navigation-block
          button#navigationSelector-previous.btn Previous
          button#navigationSelector-next.btn Next
          .source
      .stat-block
        h1 average dwell time
        #average_dwell_time
      .stat-block
        h1 unique visitors
        #unique_visitors
      .stat-block
        h1 repeating visitors percent
        #repeating_visitors
    #tab2.tab-pane
      iframe frameborder="0" width="1000" height="600" src="stat_tables?sub_domain=#{@sub_domain}"